version: '3.8'

services:
  web:
    container_name: blog_web
    build: ./django
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    volumes:
      - .:/home/django
    ports:
      - 8200:8000
    depends_on:
      - db

  db:
    container_name: blog_db
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod.db
    ports:
      - "5433:5432"
    restart: always
    environment:
      #- "POSTGRES_HOST_AUTH_METHOD=trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    container_name: djangoblog_nginx
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
    postgres_data:
    static_volume:
    media_volume:
